version: '3.9'

services:
  binarybluff:
    build: ./
    container_name: binarybluff
    env_file: ./env/binarybluff.env
    networks:
      - binarybluff-bridge
    ports:
      - 8761:${BINARYBLUFF_PORT}
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8761 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  gateway:
    build: ./gateway
    container_name: gateway
    env_file:
      - ./env/gateway.env
      - ./env/binarybluff.env
    networks:
      - binarybluff-bridge
    ports:
      - 8080:${GATEWAY_PORT}
    restart: unless-stopped
    depends_on:
      binarybluff:
        condition: service_healthy

  mensagens:
    build: ./mensagens
    container_name: mensagens
    env_file:
      - ./env/mensagens.env
      - ./env/binarybluff.env
    networks:
      - binarybluff-bridge
    restart: unless-stopped
    depends_on:
      mensagens-db:
        condition: service_started
      binarybluff:
        condition: service_healthy

  chat:
    build: ./chat
    container_name: chat
    env_file:
      - ./env/chat.env
      - ./env/binarybluff.env
    networks:
      - binarybluff-bridge
    restart: unless-stopped
    depends_on:
      binarybluff:
        condition: service_healthy

  mensagens-db:
    build: ./mensagens/mongo
    container_name: mensagens-db
    env_file: ./env/mongo.env
    networks:
      - binarybluff-bridge
    ports:
      - 27017:27017
    restart: unless-stopped

  main-db:
    image: postgres:latest
    container_name: main-db
    env_file: ./env/postgres.env
    networks:
      - binarybluff-bridge
    ports:
      - 5432:5432
    restart: unless-stopped

networks:
  binarybluff-bridge:
    driver: bridge
