version: '3.9'

services:
  mensagens-db:
    build: ./mongo
    container_name: mensagens-db
    environment:
      - MONGO_INITDB_DATABASE=naonaoa
      - MONGO_INITDB_ROOT_USERNAME=rapha
      - MONGO_INITDB_ROOT_PASSWORD=abc@1234
    networks:
      - naonaoa-bridge
    ports:
      - 27017:27017

  main-db:
    image: postgres:latest
    container_name: main-db
    environment:
      - POSTGRES_DB=naonaoa
      - POSTGRES_USER=rapha
      - POSTGRES_PASSWORD=abc@1234
    networks:
      - naonaoa-bridge
    ports:
      - 5432:5432

networks:
  naonaoa-bridge:
    driver: bridge
