version: '3.9'

services:
  binarybluff:
    build: ./
    container_name: binarybluff
    networks:
      - binarybluff-bridge
    ports:
      - 8080:8080
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  mensagens:
    build: ./mensagens
    container_name: mensagens
    env_file: ./env/mensagens.env
    networks:
      - binarybluff-bridge
    depends_on:
      mensagens-db:
        condition: service_started
      binarybluff:
        condition: service_healthy

  mensagens-db:
    build: ./mensagens/mongo
    container_name: mensagens-db
    env_file: ./env/mongo.env
    networks:
      - binarybluff-bridge
    ports:
      - 27017:27017

  main-db:
    image: postgres:latest
    container_name: main-db
    env_file: ./env/postgres.env
    networks:
      - binarybluff-bridge
    ports:
      - 5432:5432

networks:
  binarybluff-bridge:
    driver: bridge
