version: '3.9'

services:
  mensagens-db:
    build: ./mongo
    container_name: mensagens-db
    env_file: ./env/mongo.env
    networks:
      - naonaoa-bridge
    ports:
      - 27017:27017

  main-db:
    image: postgres:latest
    container_name: main-db
    env_file: ./env/postgres.env
    networks:
      - naonaoa-bridge
    ports:
      - 5432:5432

networks:
  naonaoa-bridge:
    driver: bridge
